<?php

return [
    [
        'title' => 'Elvo App — E-Commerce Platform',
        'category' => 'laravel',
        'image' => 'pdfs/elvoapp.png',
        'desc' => 'Full-featured e-commerce platform with product management, shopping cart, payment integration, and admin dashboard.',
        'full_desc' => 'Elvo App adalah platform e-commerce modern yang dibangun dengan Laravel dan Tailwind CSS. Aplikasi ini mendukung manajemen produk lengkap, sistem keranjang belanja real-time, integrasi payment gateway, serta dashboard admin yang intuitif. Dengan arsitektur MVC yang terstruktur, Elvo App memberikan pengalaman berbelanja yang cepat, aman, dan responsif di berbagai perangkat.',
        'features' => [
            'Manajemen produk dengan CRUD lengkap & upload gambar',
            'Sistem keranjang belanja real-time dengan Alpine.js',
            'Integrasi payment gateway (Midtrans)',
            'Admin dashboard dengan statistik penjualan interaktif',
            'Autentikasi multi-role (admin & customer)',
            'Responsive design mobile-first dengan Tailwind CSS',
        ],
        'tags' => ['Laravel', 'Tailwind CSS', 'MySQL', 'Alpine.js'],
        'url' => 'https://github.com/Rehanfzn/ELVOAPP_V2',
        'repo' => 'Rehanfzn/ELVOAPP_V2',

    ],
    [
        'title' => 'Data Analytics Dashboard',
        'category' => 'frontend',
        'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
        'desc' => 'Real-time data analytics dashboard with interactive charts, filtering, and export capabilities.',
        'full_desc' => 'A real-time data analytics dashboard built with Laravel and Livewire. Features interactive charts powered by Chart.js, dynamic filtering, and data export to multiple formats. Designed for business intelligence teams to monitor KPIs and make data-driven decisions.',
        'features' => [
            'Interactive charts with Chart.js',
            'Real-time data updates via Livewire',
            'Advanced filtering & date range picker',
            'CSV/PDF export functionality',
            'Customizable dashboard widgets',
        ],
        'tags' => ['Laravel', 'Livewire', 'Tailwind', 'Chart.js'],
        'url' => 'https://github.com/Rehanfzn',
        'repo' => 'Rehanfzn',
    ],
    [
        'title' => 'Inventory Management System',
        'category' => 'laravel',
        'image' => 'https://images.unsplash.com/photo-1587620962725-abab7fe55159?auto=format&fit=crop&w=800&q=80',
        'desc' => 'A comprehensive inventory management application for tracking stock, managing suppliers, and generating reports.',
        'full_desc' => 'A comprehensive inventory management system built with Laravel and MySQL. Tracks stock levels across multiple warehouses, manages supplier relationships, generates detailed reports, and provides alert notifications for low-stock items.',
        'features' => [
            'Multi-warehouse stock tracking',
            'Supplier & purchase order management',
            'Low-stock alert notifications',
            'Barcode scanning support',
            'Detailed inventory reports & analytics',
        ],
        'tags' => ['PHP 8.2', 'Laravel', 'MySQL'],
        'url' => 'https://github.com/Rehanfzn',
        'repo' => 'Rehanfzn',
    ],
    [
        'title' => 'RESTful API Service',
        'category' => 'backend',
        'image' => 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=800&q=80',
        'desc' => 'Scalable REST API built with Laravel Sanctum authentication, resource controllers, and API resource transformations.',
        'full_desc' => 'A scalable RESTful API built with Laravel, featuring Sanctum token-based authentication, resource controllers, API resource transformations, rate limiting, and comprehensive request validation.',
        'features' => [
            'Token-based authentication with Laravel Sanctum',
            'RESTful resource controllers & API resources',
            'Rate limiting & throttling',
            'Request validation & error handling',
            'API documentation with Scribe',
        ],
        'tags' => ['Laravel', 'REST API', 'Sanctum'],
        'url' => 'https://github.com/Rehanfzn',
        'repo' => 'Rehanfzn',
    ],
    [
        'title' => 'Personal Portfolio Website',
        'category' => 'frontend',
        'image' => 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
        'desc' => 'This portfolio — built with Laravel, Tailwind CSS, and Alpine.js.',
        'full_desc' => 'Personal portfolio website showcasing projects, experience, and skills. Built with Laravel 13, Tailwind CSS v4, and Alpine.js. Features dark mode, smooth scroll animations, responsive design, and an interactive photo viewer with 3D rotation.',
        'features' => [
            'Dark mode with system preference detection',
            'Smooth scroll animations & reveal effects',
            'Fully responsive mobile-first design',
            'Interactive 3D photo viewer',
            'Dynamic Island-style navigation',
            'Aurora animated background effect',
        ],
        'tags' => ['Laravel', 'Tailwind', 'Alpine.js'],
        'url' => 'https://github.com/Rehanfzn',
        'repo' => 'Rehanfzn',
    ],
    [
        'title' => 'Real-Time Chat Application',
        'category' => 'laravel',
        'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=800&q=80',
        'desc' => 'Real-time messaging app with typing indicators, read receipts, and group chats.',
        'full_desc' => 'Real-time chat application powered by Laravel Reverb WebSocket server. Features instant messaging, typing indicators, read receipts, group chat functionality, and online presence indicators. Built with a focus on performance and scalability.',
        'features' => [
            'Real-time messaging with Laravel Reverb',
            'Typing indicators & read receipts',
            'Group chat & private messaging',
            'Online presence indicators',
            'Message history & search',
        ],
        'tags' => ['Laravel', 'Reverb', 'WebSocket', 'Tailwind'],
        'url' => 'https://github.com/Rehanfzn',
        'repo' => 'Rehanfzn',
    ],
];
